// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: message.proto

package pique

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Block_State int32

const (
	Block_SUCCEDED Block_State = 0
	Block_FAILED   Block_State = 1
	Block_PENDING  Block_State = 2
)

var Block_State_name = map[int32]string{
	0: "SUCCEDED",
	1: "FAILED",
	2: "PENDING",
}

var Block_State_value = map[string]int32{
	"SUCCEDED": 0,
	"FAILED":   1,
	"PENDING":  2,
}

func (x Block_State) String() string {
	return proto.EnumName(Block_State_name, int32(x))
}

func (Block_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1, 0}
}

type Job struct {
	GlobalOptions        *GlobalOptions `protobuf:"bytes,1,opt,name=global_options,json=globalOptions,proto3" json:"global_options,omitempty"`
	Block                []*Block       `protobuf:"bytes,2,rep,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}
func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetGlobalOptions() *GlobalOptions {
	if m != nil {
		return m.GlobalOptions
	}
	return nil
}

func (m *Job) GetBlock() []*Block {
	if m != nil {
		return m.Block
	}
	return nil
}

type Block struct {
	Id                 int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId           int32  `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	ChildId            int32  `protobuf:"varint,3,opt,name=child_id,json=childId,proto3" json:"child_id,omitempty"`
	BlockName          string `protobuf:"bytes,4,opt,name=block_name,json=blockName,proto3" json:"block_name,omitempty"`
	PluginName         string `protobuf:"bytes,5,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	PluginFunctionName string `protobuf:"bytes,6,opt,name=plugin_function_name,json=pluginFunctionName,proto3" json:"plugin_function_name,omitempty"`
	//String argument that can be converted to json.
	PluginFunctionArguments string      `protobuf:"bytes,7,opt,name=plugin_function_arguments,json=pluginFunctionArguments,proto3" json:"plugin_function_arguments,omitempty"`
	State                   Block_State `protobuf:"varint,8,opt,name=state,proto3,enum=pique.Block_State" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}    `json:"-"`
	XXX_unrecognized        []byte      `json:"-"`
	XXX_sizecache           int32       `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}
func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Block) GetParentId() int32 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *Block) GetChildId() int32 {
	if m != nil {
		return m.ChildId
	}
	return 0
}

func (m *Block) GetBlockName() string {
	if m != nil {
		return m.BlockName
	}
	return ""
}

func (m *Block) GetPluginName() string {
	if m != nil {
		return m.PluginName
	}
	return ""
}

func (m *Block) GetPluginFunctionName() string {
	if m != nil {
		return m.PluginFunctionName
	}
	return ""
}

func (m *Block) GetPluginFunctionArguments() string {
	if m != nil {
		return m.PluginFunctionArguments
	}
	return ""
}

func (m *Block) GetState() Block_State {
	if m != nil {
		return m.State
	}
	return Block_SUCCEDED
}

type GlobalOptions struct {
	LogLevel             string   `protobuf:"bytes,1,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Checkfrequency       int32    `protobuf:"varint,3,opt,name=checkfrequency,proto3" json:"checkfrequency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GlobalOptions) Reset()         { *m = GlobalOptions{} }
func (m *GlobalOptions) String() string { return proto.CompactTextString(m) }
func (*GlobalOptions) ProtoMessage()    {}
func (*GlobalOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}
func (m *GlobalOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GlobalOptions.Unmarshal(m, b)
}
func (m *GlobalOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GlobalOptions.Marshal(b, m, deterministic)
}
func (m *GlobalOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GlobalOptions.Merge(m, src)
}
func (m *GlobalOptions) XXX_Size() int {
	return xxx_messageInfo_GlobalOptions.Size(m)
}
func (m *GlobalOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_GlobalOptions.DiscardUnknown(m)
}

var xxx_messageInfo_GlobalOptions proto.InternalMessageInfo

func (m *GlobalOptions) GetLogLevel() string {
	if m != nil {
		return m.LogLevel
	}
	return ""
}

func (m *GlobalOptions) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GlobalOptions) GetCheckfrequency() int32 {
	if m != nil {
		return m.Checkfrequency
	}
	return 0
}

func init() {
	proto.RegisterEnum("pique.Block_State", Block_State_name, Block_State_value)
	proto.RegisterType((*Job)(nil), "pique.Job")
	proto.RegisterType((*Block)(nil), "pique.Block")
	proto.RegisterType((*GlobalOptions)(nil), "pique.GlobalOptions")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 384 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0x4d, 0x6b, 0x9c, 0x50,
	0x14, 0x86, 0xab, 0x13, 0x47, 0x3d, 0x66, 0x64, 0x38, 0x04, 0x6a, 0x28, 0xa5, 0xe2, 0xa2, 0xb8,
	0x92, 0x32, 0xdd, 0xb5, 0xab, 0x24, 0x9a, 0x60, 0x09, 0xd3, 0x62, 0xe8, 0xa6, 0x1b, 0xf1, 0xe3,
	0x8e, 0x23, 0xb9, 0x7a, 0x8d, 0x1f, 0x85, 0xfe, 0xd2, 0xfe, 0x9d, 0xe2, 0xb9, 0x16, 0x32, 0xb3,
	0xf3, 0x3c, 0xcf, 0xfb, 0x5e, 0xb8, 0xc7, 0x0b, 0x9b, 0x86, 0x0d, 0x43, 0x56, 0xb1, 0xa0, 0xeb,
	0xc5, 0x28, 0x50, 0xeb, 0xea, 0x97, 0x89, 0x79, 0x07, 0x58, 0x7d, 0x13, 0x39, 0x7e, 0x05, 0xbb,
	0xe2, 0x22, 0xcf, 0x78, 0x2a, 0xba, 0xb1, 0x16, 0xed, 0xe0, 0x28, 0xae, 0xe2, 0x5b, 0xbb, 0xab,
	0x80, 0x62, 0xc1, 0x03, 0xc9, 0xef, 0xd2, 0x25, 0x9b, 0xea, 0xf5, 0x88, 0x1e, 0x68, 0x39, 0x17,
	0xc5, 0xb3, 0xa3, 0xba, 0x2b, 0xdf, 0xda, 0x5d, 0x2e, 0x9d, 0xdb, 0x99, 0x25, 0x52, 0x79, 0x7f,
	0x55, 0xd0, 0x08, 0xa0, 0x0d, 0x6a, 0x5d, 0xd2, 0xf1, 0x5a, 0xa2, 0xd6, 0x25, 0xbe, 0x03, 0xb3,
	0xcb, 0x7a, 0xd6, 0x8e, 0x69, 0x5d, 0x3a, 0x2a, 0x61, 0x43, 0x82, 0xb8, 0xc4, 0x6b, 0x30, 0x8a,
	0x63, 0xcd, 0xcb, 0xd9, 0xad, 0xc8, 0xe9, 0x34, 0xc7, 0x25, 0xbe, 0x07, 0xa0, 0xa3, 0xd3, 0x36,
	0x6b, 0x98, 0x73, 0xe1, 0x2a, 0xbe, 0x99, 0x98, 0x44, 0xf6, 0x59, 0xc3, 0xf0, 0x03, 0x58, 0x1d,
	0x9f, 0xaa, 0xba, 0x95, 0x5e, 0x23, 0x0f, 0x12, 0x51, 0xe0, 0x13, 0x5c, 0x2d, 0x81, 0xc3, 0xd4,
	0x16, 0xf3, 0x4d, 0x64, 0x72, 0x4d, 0x49, 0x94, 0xee, 0x7e, 0x51, 0xd4, 0xf8, 0x02, 0xd7, 0xe7,
	0x8d, 0xac, 0xaf, 0xa6, 0x86, 0xb5, 0xe3, 0xe0, 0xe8, 0x54, 0x7b, 0x7b, 0x5a, 0xbb, 0xf9, 0xaf,
	0xd1, 0x07, 0x6d, 0x18, 0xb3, 0x91, 0x39, 0x86, 0xab, 0xf8, 0xf6, 0x0e, 0x5f, 0xef, 0x28, 0x78,
	0x9a, 0x4d, 0x22, 0x03, 0x5e, 0x00, 0x1a, 0xcd, 0x78, 0x09, 0xc6, 0xd3, 0xcf, 0xbb, 0xbb, 0x28,
	0x8c, 0xc2, 0xed, 0x1b, 0x04, 0x58, 0xdf, 0xdf, 0xc4, 0x8f, 0x51, 0xb8, 0x55, 0xd0, 0x02, 0xfd,
	0x47, 0xb4, 0x0f, 0xe3, 0xfd, 0xc3, 0x56, 0xf5, 0x8e, 0xb0, 0x39, 0xf9, 0x3b, 0xf3, 0x42, 0xb9,
	0xa8, 0x52, 0xce, 0x7e, 0x33, 0x4e, 0x7b, 0x36, 0x13, 0x83, 0x8b, 0xea, 0x71, 0x9e, 0x11, 0xe1,
	0x82, 0x6e, 0xa9, 0x12, 0xa7, 0x6f, 0xfc, 0x08, 0x76, 0x71, 0x64, 0xc5, 0xf3, 0xa1, 0x67, 0x2f,
	0x13, 0x6b, 0x8b, 0x3f, 0xcb, 0xaa, 0xcf, 0xe8, 0xad, 0xfe, 0x4b, 0x3e, 0x9a, 0x7c, 0x4d, 0x4f,
	0xe8, 0xf3, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x21, 0xec, 0x39, 0xd1, 0x53, 0x02, 0x00, 0x00,
}
